trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

variables:
- group: Azure

stages:
  - stage: Plan
    displayName: "Terraform plan on dev"
    jobs:
      - job: PR_Plan
        displayName: "Terraform Plan on PR"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Ініціалізація Terraform
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: $(ServiceConnection)
              backendAzureRmResourceGroupName: $(backendGroup)
              backendAzureRmStorageAccountName: $(backendStorage)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
            displayName: "Terraform Init"

          # Вибір або створення workspace
          - script: |
              terraform workspace select dev || terraform workspace new dev
            displayName: "Select/Create Terraform Workspace"
            workingDirectory: $(System.DefaultWorkingDirectory)/terraform

          # Валідація Terraform файлів
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
            displayName: "Terraform Validate"

          # Виконання Terraform Plan
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: $(ServiceConnection)
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
            displayName: "Terraform Plan"
