trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

variables:
- group: Azure

stages:
  - stage: Plan
    displayName: "Terraform plan on dev"
    jobs:
      - job: PR_Plan
        displayName: "Terraform Plan on PR"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              cd terraform
            displayName: "Change dir"

          # Ініціалізація Terraform
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: $(ServiceConnection)
              backendAzureRmResourceGroupName: $(backendGroup)
              backendAzureRmStorageAccountName: $(backendStorage)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)
            displayName: "Terraform Init"
          
          - script: |
              terraform workspace select dev || terraform workspace new dev
            displayName: "Select/Create Terraform Workspace"

          # Валідація Terraform файлів
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
            displayName: "Terraform Validate"

          # Виконання Terraform Plan
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: $(ServiceConnection)
            displayName: "Terraform Plan"
